mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^private-chat/', include('private_chat.urls', namespace='private-chat')),
    url(r'^admin/', include(admin.site.urls)),
)

private_chat/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from private_chat import views


urlpatterns = patterns('',
    url('^$', RedirectView.as_view(url=reverse_lazy('private-chat:profile')), name='index'),
    url('^profile/$', views.Profile.as_view(), name='profile'),
    url('^chats/(?P<username>.*?)/$', views.Chat.as_view(), name='chat'),
    url('^login/$', 'django.contrib.auth.views.login', kwargs={'template_name': 'private_chat/login.html'},
        name='login'),
    url('^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
)

tornado_app/urls.py
from tornado_app import websockets

urlpatterns = [
    (r'/messages', websockets.MessageHandler),
    (r'/contacts', websockets.ContactsHandler),
    (r'/contactrequests', websockets.ContactRequestsHandler),
]

private_chat/models.py
from itertools import chain

from django.db import models
from django.contrib.auth.models import User, UserManager


class ChatUser(models.Model):
    user = models.OneToOneField(User)
    objects = UserManager()

    def get_username(self):
        return self.user.get_username()

    def contacts(self):
        return chain(
            map(lambda x: x.requester, self.contact_accepted.all()),
            map(lambda x: x.accepter, self.contact_requested.all())
        )

    def messages(self, otheruser):
        return sorted(list(chain(
            self.message_receiver.filter(sender=otheruser),
            self.message_sender.filter(receiver=otheruser),
        )), key=lambda x: x.created)


class Message(models.Model):
    sender = models.ForeignKey(ChatUser, related_name="message_sender")
    receiver = models.ForeignKey(ChatUser, related_name="message_receiver")
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0} [{1}]: {2}".format(self.created.strftime('%H:%M:%S'), self.sender.get_username(), self.message)


class Contact(models.Model):
    requester = models.ForeignKey(ChatUser, related_name="contact_requested")
    accepter = models.ForeignKey(ChatUser, related_name="contact_accepted")


class ContactRequest(models.Model):
    accepter = models.ForeignKey(ChatUser, related_name="contact_accepter")
    requester = models.ForeignKey(ChatUser, related_name="contact_requester")
    message = models.TextField(null=True, blank=True)

tornado_app/models.py
import datetime
import sqlite3


conn = sqlite3.connect("db.sqlite3")


def get_user_id(username):
    return conn.execute("SELECT id FROM auth_user WHERE username = :username",
                        {"username": username}).fetchone()[0]


def add_message(sender, receiver, message):
    created = datetime.datetime.now()
    conn.execute(
        "INSERT INTO private_chat_message (sender_id, receiver_id, message, created)"
        " VALUES (:sender_id, :receiver_id, :message, :created)",
        {
            "sender_id": get_user_id(sender),
            "receiver_id": get_user_id(receiver),
            "message": message,
            "created": created,
        }
    )
    conn.commit()
    return created


def add_contact(accepter, requester):
    accepter_id = get_user_id(accepter)
    requester_id = get_user_id(requester)
    print("{0}({1}) accepted request from {2}({3})".format(accepter, accepter_id, requester, requester_id))
    conn.execute(
        "INSERT INTO private_chat_contact (accepter_id, requester_id)"
        " VALUES (:accepter_id, :requester_id)",
        {
            "accepter_id": accepter_id,
            "requester_id": requester_id,
        }
    )
    conn.execute(
        "DELETE FROM private_chat_contactrequest"
        " WHERE accepter_id = :accepter_id"
        " AND requester_id = :requester_id",
        {
            "accepter_id": accepter_id,
            "requester_id": requester_id,
        }
    )
    conn.commit()


def add_contact_request(requester, accepter):
    accepter_id = get_user_id(accepter)
    requester_id = get_user_id(requester)
    print("{0}({1}) requested contact from {2}({3})".format(requester, requester_id, accepter, accepter_id))
    conn.execute(
        "INSERT INTO private_chat_contactrequest (accepter_id, requester_id)"
        " VALUES (:accepter_id, :requester_id)",
        {
            "accepter_id": accepter_id,
            "requester_id": requester_id,
        }
    )
    conn.commit()

private_chat/views.py
from django.views.generic import TemplateView
from braces.views import LoginRequiredMixin
from django.contrib.auth.models import User


class ChatTemplate:
    def get_context_data(self, **kwargs):
        context = super(ChatTemplate, self).get_context_data(**kwargs)
        context['chatuser'] = self.request.user.chatuser
        return context


class Profile(LoginRequiredMixin, ChatTemplate, TemplateView):
    template_name = "private_chat/profile.html"


class Chat(LoginRequiredMixin, ChatTemplate, TemplateView):
    template_name = "private_chat/chat.html"

    def get_context_data(self, **kwargs):
        context = super(Chat, self).get_context_data(**kwargs)
        otheruser = User.objects.get(username=self.kwargs['username']).chatuser
        context['other_chatuser'] = otheruser
        context['chat_messages'] = self.request.user.chatuser.messages(otheruser)
        return context

private_chat/templates/private_chat/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}{% endblock %}
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

private_chat/templates/private_chat/chat.html
{% extends "private_chat/base.html" %}
{% block styles %}
    <style>
        .scroll {
            overflow-x: scroll;
            overflow-y: scroll;
        }
        #message-div {
            height: 150px;
            width: 1000px;
        }
        #m {
            width: 1000px;
        }
    </style>
{% endblock %}
{% block content %}
    <p>Chats between <a href="{% url 'private-chat:profile' %}">you</a> and {{ other_chatuser.get_username }}:</p>
    <div id="message-div" class="scroll">
        <ul id="messages">
            {% for message in chat_messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    <input type="text" id="m">
{% endblock %}
{% block scripts %}
    <script>
        var context = {
            other_username: "{{ other_chatuser.get_username }}",
            username: "{{ chatuser.get_username }}"
        };
        var socket = new WebSocket("ws://localhost:8888/messages");
        socket.onmessage = function (e) {
            console.log("got: "+ e.data);
            var message = JSON.parse(e.data);
            if ((message.receiver === context.username && message.sender === context.other_username) ||
               (message.receiver === context.other_username && message.sender === context.username)) {
                $("#messages").append($("<li>").text(message.message));
                fix_scroll();
            }
        };
        function fix_scroll() {
            var e = $("#message-div");
            e.scrollTop(e.prop("scrollHeight"));
        }
        function on_message_keyup(event){
            var message_input = $("#m");
            if (event.keyCode === 13) {
                var message = message_input.val();
                console.log("sending: " + message);
                socket.send(JSON.stringify({
                    "message": message,
                    "sender": context.username,
                    "receiver": context.other_username
                }));
                message_input.val("");
                message_input.focus();
            }
        }
        $(document).ready(function () {
            var message_input = $("#m");
            message_input.focus();
            message_input.keyup(on_message_keyup);
            fix_scroll();
        });
    </script>
{% endblock %}

private_chat/templates/private_chat/login.html
{% extends "private_chat/base.html" %}
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'private-chat:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

private_chat/templates/private_chat/profile.html
{% extends "private_chat/base.html" %}
{% block content %}
    <p>Hello, {{ chatuser.get_username }} (<a href="{% url 'private-chat:logout' %}">Logout</a>)</p>
    <p>Contacts:</p>
    <ul id="contacts">
        {% for contact in chatuser.contacts %}
            <li><a href="{% url 'private-chat:chat' contact.get_username %}">{{ contact.get_username }}</a></li>
        {% endfor %}
    </ul>
    <p>Contacts pending:</p>
    <ul id="contacts-pending">
        {% for contact in chatuser.contact_accepter.all %}
            <li id="pending-{{ contact.requester.get_username }}">
                <span>{{ contact.requester.get_username }}</span>
                <a data-name="{{ contact.requester.get_username }}" class="accept-btn">Accept</a>
            </li>
        {% endfor %}
    </ul>
    <p>Contacts requested:</p>
    <ul id="contacts-requested">
        {% for contact in chatuser.contact_requester.all %}
            <li id="requested-{{ contact.accepter.get_username }}">{{ contact.accepter.get_username }}</li>
        {% endfor %}
    </ul>
    <p>Request a contact:</p>
    <input id="contact-username" type="text" placeholder="username">
    <input id="contact-request-btn" type="button" value="Request">
{% endblock %}
{% block scripts %}
    <script>
        var context = {
            username: "{{ chatuser.get_username }}",
            chat_url: "{% url 'private-chat:chat' 'blah' %}"
        };
        function get_chat_url(username) {
            return context.chat_url.replace('blah', username);
        }
        var contacts_socket = new WebSocket("ws://localhost:8888/contacts");
        var contact_requests_socket = new WebSocket("ws://localhost:8888/contactrequests");
        contacts_socket.onmessage = function (e) {
            console.log("got: "+ e.data);
            var data = JSON.parse(e.data);
            var to_add;
            if (data.accepter === context.username) {
                to_add = data.requester;
                $("#pending-"+to_add).remove();
            } else if (data.requester === context.username) {
                to_add = data.accepter;
                $("#requested-"+to_add).remove();
            }
            if (to_add) {
                $("#contacts").append(
                    $("<li>").append(
                        $("<a>")
                        .attr("href", get_chat_url(to_add))
                        .text(to_add)
                    )
                );
            }
        };
        var on_click_accept = function (){
            var requester = this.getAttribute('data-name');
            var accepter = context.username;
            var message = JSON.stringify({
                requester: requester,
                accepter: accepter
            });
            console.log(message);
            contacts_socket.send(message);
            this.parentNode.remove();
        };
        $(".accept-btn").click(on_click_accept);
        $("#contact-request-btn").click(function (){
            var requester = context.username;
            var accepter = $("#contact-username").val();
            var message = JSON.stringify({
                requester: requester,
                accepter: accepter
            });
            console.log(message);
            contact_requests_socket.send(message);
        });
        contact_requests_socket.onmessage = function (e) {
            console.log("got: "+ e.data);
            var data = JSON.parse(e.data);
            if (data.accepter === context.username) {
                $("#contacts-pending").append(
                    $("<li>")
                    .attr("id", "pending-"+data.requester)
                    .append(
                        $("<span>")
                        .text(data.requester)
                    )
                    .append(
                        $("<a>")
                        .attr("data-name", data.requester)
                        .addClass("accept-btn")
                        .text(" Accept")
                        .click(on_click_accept)
                    )
                );
            } else if (data.requester === context.username) {
                $("#contacts-requested").append(
                    $("<li>")
                    .attr("id", "requested-"+data.accepter)
                    .text(data.accepter)
                );
            }
        };
    </script>
{% endblock %}